#pragma once

#define Airbrakes_CFG_TelemetryBufferSize 512
#define Airbrakes_CFG_LogBufferSize 512

#define Airbrakes_CFG_TelemetryRefreshPeriod_ms 100
#define Airbrakes_CFG_SerialRefreshPeriod_ms 10

#define Airbrakes_CFG_CommandLocalStringBufferSize 64